import type { Metadata } from "next";
import {  Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import { ThemeProvider } from "next-themes";

import Footer from "@/components/Footer/Footer";
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.variable}  antialiased`}
      >
        
            <ThemeProvider 
        attribute='class'
        defaultTheme="light"
        enableSystem
        disableTransitionOnChange
        >


        <Header />
        {children}
        <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
